version: '3.8'

services:
  rtpengine:
     image: docker.resaa.net/rtpengine:fonoster-based-1
     container_name: rmgw
     command: rtpengine -L 200 --num-threads=16 --interface=172.16.100.76 --listen-ng=0.0.0.0:2223 --listen-cli=localhost:2224 --measure-rtp --port-min=30000 --port-max=40000 --log-level=3
     network_mode: host
     volumes:
       - /lib/modules:/lib/modules
       - ./media:/media

  # db:
  #   image: docker.resaa.net/library/mysql:8.0
  #   container_name: my_sql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=passwd
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./mysql:/var/lib/mysql
      # - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: docker.resaa.net/redis
    container_name: redis
    ports:
      - 6379:6379


  pcscf:
    # image: docker.resaa.net/ghcr.io/kamailio/kamailio:5.8.2-bookworm
    # image: kamailio-master:latest
    image: ghcr.io/kamailio/kamailio-ci
    container_name: pcscf
    network_mode: host
    depends_on:
      # - db
      - redis
    cap_add:
      - NET_RAW
    environment:
      LISTENING_IP: 172.16.100.76
      LISTENING_PORT: 5060
    volumes:
      - ./:/etc/kamailio
      # - ./media:/media
  
  