

# Stage 1: Build Stage
FROM docker.resaa.net/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive


RUN apt update

# Install updates and dependencies
# RUN apt-get -y install mysql-server tcpdump screen tmux ntp ntpdate git-core dkms \
#         gcc flex bison libmysqlclient-dev make libssl-dev libcurl4-openssl-dev \
#         libxml2-dev libpcre2-dev bash-completion g++ autoconf libmnl-dev \
#         libsctp-dev libradcli-dev libradcli4 libjson-c-dev pkg-config iproute2 net-tools \
#         iputils-ping libgcrypt20-dev libjansson-dev libevent-dev libnghttp2-dev uuid-dev
#ipsec-tools

RUN apt update && apt -y install mysql-server tcpdump screen ntp ntpdate git-core dkms \
        gcc flex bison libmysqlclient-dev make libssl-dev libcurl4-openssl-dev \
        libxml2-dev libpcre2-dev bash-completion g++ autoconf libmnl-dev \
        libsctp-dev libradcli-dev libradcli4 libjson-c-dev pkg-config iproute2 net-tools \
        iputils-ping libgcrypt20-dev libjansson-dev libevent-dev libnghttp2-dev uuid-dev 

COPY ./kamailio /usr/local/src/kamailio-5.8/kamailio/

WORKDIR /usr/local/src/kamailio-5.8/kamailio

RUN make exclude_modules="" cfg

RUN export RADCLI=1 && make Q=0 all | tee make_all.txt && make install | tee make_install.txt && ldconfig

RUN rm -rf /usr/share/doc /usr/share/man /usr/share/info /usr/local/src/kamailio-5.8 \
        /var/lib/apt/lists/* && echo "root:a" | chpasswd && apt remove -y git-core\
        gcc g++ make && apt autoremove -y && apt clean 

RUN rm -rf /tmp/* /var/tmp/*

CMD ["kamailio", "-f", "/etc/kamailio/kamailio.cfg", "-P", "/kamailio.pid", "-DD", "-E", "-e"]

